name: vrp
channels:
  - conda-forge
dependencies:
  - python
  # - ortools-python
  - pytest
  - pyyaml
  - unidecode
  - flask
  - Flask-SocketIO
  - python-engineio
  - python-socketio
  - Flask
  - Werkzeug
# - opencv-python
  - numpy
  
# Install gmplot using pip install gmplot
# Install opencv manually
# Install ortools manually
# pip install flask-babel